FROM hrvg/aigeomorphologist:latest
COPY . /home/rstudio/project/
RUN cd /home/rstudio/project/ && \ 
	R -e "withr::with_libpaths('/usr/local/lib/R/site-library', devtools::install_deps(dependencies = TRUE, build = FALSE))"